server:
  port: 8077
spring:
  redis:
    host: 117.72.106.162
    port: 6379
    password: process
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 8
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

justauth:
  enabled: true
  type:
    WEIBO:
      client-id: 1716655542
      client-secret: 6ec4b6abda75f48ccbb64e4265ca1f70
      redirect-uri: http://2bf52992.r1.cpolar.top/oauth/weibo/callback
  cache:
    type: redis
    prefix: 'SOCIAL::STATE::'
    timeout: 1h